-- ========================================================
-- Supabase Cloud Schema for project_fiveper (Student Progress Tracking)
-- Universal Idempotent Schema V2.1-FINAL (Runs anywhere without errors)
-- Execute this SQL in Supabase SQL Editor (https://supabase.com/dashboard)
-- ========================================================

-- 1. Table: pf_users
CREATE TABLE IF NOT EXISTS pf_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('ผู้ดูแลระบบ', 'อาจารย์', 'นักศึกษา')),
  password_hash TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Table: pf_projects
CREATE TABLE IF NOT EXISTS pf_projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  course TEXT NOT NULL,
  due_date DATE,
  status TEXT DEFAULT 'กำลังดำเนินการ',
  student_id BIGINT REFERENCES pf_users(id) ON DELETE SET NULL,
  teacher_id BIGINT REFERENCES pf_users(id) ON DELETE SET NULL,
  student TEXT,
  progress INT DEFAULT 0,
  attachment_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Table: pf_project_members (Junction Table for Group Projects - FR-3.1)
CREATE TABLE IF NOT EXISTS pf_project_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT REFERENCES pf_projects(id) ON DELETE CASCADE,
  student_id BIGINT REFERENCES pf_users(id) ON DELETE CASCADE,
  role_in_team TEXT DEFAULT 'สมาชิก' CHECK (role_in_team IN ('หัวหน้าโครงการ', 'สมาชิก')),
  joined_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Table: pf_milestones
CREATE TABLE IF NOT EXISTS pf_milestones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT REFERENCES pf_projects(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  due_date DATE,
  status TEXT DEFAULT 'ยังไม่เริ่ม',
  progress INT DEFAULT 0,
  is_approved BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Table: pf_feedback
CREATE TABLE IF NOT EXISTS pf_feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT REFERENCES pf_projects(id) ON DELETE CASCADE,
  instructor_id BIGINT REFERENCES pf_users(id) ON DELETE SET NULL,
  comment TEXT NOT NULL,
  instructor_name TEXT,
  date DATE DEFAULT CURRENT_DATE,
  project_name TEXT,
  is_read BOOLEAN DEFAULT FALSE,
  reply_comment TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Table: pf_notifications
CREATE TABLE IF NOT EXISTS pf_notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES pf_users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Table: pf_audit_logs
CREATE TABLE IF NOT EXISTS pf_audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES pf_users(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  details TEXT,
  ip_address TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Table: pf_chart
CREATE TABLE IF NOT EXISTS pf_chart (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course TEXT NOT NULL,
  projects INT DEFAULT 0,
  completed INT DEFAULT 0,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE pf_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE pf_projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE pf_project_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE pf_milestones ENABLE ROW LEVEL SECURITY;
ALTER TABLE pf_feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE pf_notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE pf_audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE pf_chart ENABLE ROW LEVEL SECURITY;

-- Drop Policies if exist before creating (Idempotent Safe Policies)
DROP POLICY IF EXISTS "Allow public read pf_users" ON pf_users;
DROP POLICY IF EXISTS "Allow public insert pf_users" ON pf_users;
DROP POLICY IF EXISTS "Allow public update pf_users" ON pf_users;
DROP POLICY IF EXISTS "Allow public delete pf_users" ON pf_users;

CREATE POLICY "Allow public read pf_users" ON pf_users FOR SELECT USING (true);
CREATE POLICY "Allow public insert pf_users" ON pf_users FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update pf_users" ON pf_users FOR UPDATE USING (true);
CREATE POLICY "Allow public delete pf_users" ON pf_users FOR DELETE USING (true);

DROP POLICY IF EXISTS "Allow public read pf_projects" ON pf_projects;
DROP POLICY IF EXISTS "Allow public insert pf_projects" ON pf_projects;
DROP POLICY IF EXISTS "Allow public update pf_projects" ON pf_projects;
DROP POLICY IF EXISTS "Allow public delete pf_projects" ON pf_projects;

CREATE POLICY "Allow public read pf_projects" ON pf_projects FOR SELECT USING (true);
CREATE POLICY "Allow public insert pf_projects" ON pf_projects FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update pf_projects" ON pf_projects FOR UPDATE USING (true);
CREATE POLICY "Allow public delete pf_projects" ON pf_projects FOR DELETE USING (true);

DROP POLICY IF EXISTS "Allow public read pf_project_members" ON pf_project_members;
DROP POLICY IF EXISTS "Allow public insert pf_project_members" ON pf_project_members;
DROP POLICY IF EXISTS "Allow public update pf_project_members" ON pf_project_members;
DROP POLICY IF EXISTS "Allow public delete pf_project_members" ON pf_project_members;

CREATE POLICY "Allow public read pf_project_members" ON pf_project_members FOR SELECT USING (true);
CREATE POLICY "Allow public insert pf_project_members" ON pf_project_members FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update pf_project_members" ON pf_project_members FOR UPDATE USING (true);
CREATE POLICY "Allow public delete pf_project_members" ON pf_project_members FOR DELETE USING (true);

DROP POLICY IF EXISTS "Allow public read pf_milestones" ON pf_milestones;
DROP POLICY IF EXISTS "Allow public insert pf_milestones" ON pf_milestones;
DROP POLICY IF EXISTS "Allow public update pf_milestones" ON pf_milestones;
DROP POLICY IF EXISTS "Allow public delete pf_milestones" ON pf_milestones;

CREATE POLICY "Allow public read pf_milestones" ON pf_milestones FOR SELECT USING (true);
CREATE POLICY "Allow public insert pf_milestones" ON pf_milestones FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update pf_milestones" ON pf_milestones FOR UPDATE USING (true);
CREATE POLICY "Allow public delete pf_milestones" ON pf_milestones FOR DELETE USING (true);

DROP POLICY IF EXISTS "Allow public read pf_feedback" ON pf_feedback;
DROP POLICY IF EXISTS "Allow public insert pf_feedback" ON pf_feedback;
DROP POLICY IF EXISTS "Allow public update pf_feedback" ON pf_feedback;
DROP POLICY IF EXISTS "Allow public delete pf_feedback" ON pf_feedback;

CREATE POLICY "Allow public read pf_feedback" ON pf_feedback FOR SELECT USING (true);
CREATE POLICY "Allow public insert pf_feedback" ON pf_feedback FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update pf_feedback" ON pf_feedback FOR UPDATE USING (true);
CREATE POLICY "Allow public delete pf_feedback" ON pf_feedback FOR DELETE USING (true);

DROP POLICY IF EXISTS "Allow public read pf_notifications" ON pf_notifications;
DROP POLICY IF EXISTS "Allow public insert pf_notifications" ON pf_notifications;

CREATE POLICY "Allow public read pf_notifications" ON pf_notifications FOR SELECT USING (true);
CREATE POLICY "Allow public insert pf_notifications" ON pf_notifications FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read pf_audit_logs" ON pf_audit_logs;
DROP POLICY IF EXISTS "Allow public insert pf_audit_logs" ON pf_audit_logs;

CREATE POLICY "Allow public read pf_audit_logs" ON pf_audit_logs FOR SELECT USING (true);
CREATE POLICY "Allow public insert pf_audit_logs" ON pf_audit_logs FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read pf_chart" ON pf_chart;
DROP POLICY IF EXISTS "Allow public insert pf_chart" ON pf_chart;
DROP POLICY IF EXISTS "Allow public update pf_chart" ON pf_chart;
DROP POLICY IF EXISTS "Allow public delete pf_chart" ON pf_chart;

CREATE POLICY "Allow public read pf_chart" ON pf_chart FOR SELECT USING (true);
CREATE POLICY "Allow public insert pf_chart" ON pf_chart FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update pf_chart" ON pf_chart FOR UPDATE USING (true);
CREATE POLICY "Allow public delete pf_chart" ON pf_chart FOR DELETE USING (true);

-- Insert Default Initial Data safely using WHERE NOT EXISTS
INSERT INTO pf_users (user_id, name, email, role)
SELECT 'ADM001', 'ผู้ดูแลระบบ', 'admin@ku.th', 'ผู้ดูแลระบบ'
WHERE NOT EXISTS (SELECT 1 FROM pf_users WHERE email = 'admin@ku.th');

INSERT INTO pf_users (user_id, name, email, role)
SELECT 'INS001', 'ดร.สมหญิง มีชัย', 'teacher@ku.th', 'อาจารย์'
WHERE NOT EXISTS (SELECT 1 FROM pf_users WHERE email = 'teacher@ku.th');

INSERT INTO pf_users (user_id, name, email, role)
SELECT 'STU001', 'สมชาย ใจดี', 'student@ku.th', 'นักศึกษา'
WHERE NOT EXISTS (SELECT 1 FROM pf_users WHERE email = 'student@ku.th');

INSERT INTO pf_users (user_id, name, email, role)
SELECT 'STU002', 'สมหญิง ใจงาม', 'somying.j@university.ac.th', 'นักศึกษา'
WHERE NOT EXISTS (SELECT 1 FROM pf_users WHERE email = 'somying.j@university.ac.th');

INSERT INTO pf_users (user_id, name, email, role)
SELECT 'INS002', 'ศ.ดร.สมชาย วิชาการ', 'somchai.w@university.ac.th', 'อาจารย์'
WHERE NOT EXISTS (SELECT 1 FROM pf_users WHERE email = 'somchai.w@university.ac.th');

INSERT INTO pf_projects (name, description, course, due_date, status, student, progress)
SELECT 'โครงการพัฒนาเว็บไซต์', 'สร้างเว็บไซต์ที่รองรับหลายขนาดหน้าจอ', 'CS 101', '2026-03-15', 'กำลังดำเนินการ', 'สมชาย ใจดี', 75
WHERE NOT EXISTS (SELECT 1 FROM pf_projects WHERE name = 'โครงการพัฒนาเว็บไซต์');

INSERT INTO pf_projects (name, description, course, due_date, status, student, progress)
SELECT 'การออกแบบฐานข้อมูล', 'ออกแบบและสร้างโครงสร้างฐานข้อมูล', 'CS 201', '2026-03-20', 'กำลังดำเนินการ', 'สมหญิง ใจงาม', 45
WHERE NOT EXISTS (SELECT 1 FROM pf_projects WHERE name = 'การออกแบบฐานข้อมูล');

INSERT INTO pf_projects (name, description, course, due_date, status, student, progress)
SELECT 'โมเดลแมชชีนเลิร์นนิง', 'ฝึกโมเดลการจำแนกประเภท', 'CS 301', '2026-04-01', 'ยังไม่เริ่ม', 'สมศักดิ์ ทรงไทย', 0
WHERE NOT EXISTS (SELECT 1 FROM pf_projects WHERE name = 'โมเดลแมชชีนเลิร์นนิง');

INSERT INTO pf_projects (name, description, course, due_date, status, student, progress)
SELECT 'แอปพลิเคชันมือถือ', 'พัฒนาแอป Android และ iOS', 'CS 101', '2026-02-28', 'เสร็จสิ้น', 'พุทธพร เหลืองสีเพชร', 100
WHERE NOT EXISTS (SELECT 1 FROM pf_projects WHERE name = 'แอปพลิเคชันมือถือ');

INSERT INTO pf_milestones (name, due_date, status, progress)
SELECT 'การวางแผนโครงการ', '2026-03-05', 'เสร็จสิ้น', 100
WHERE NOT EXISTS (SELECT 1 FROM pf_milestones WHERE name = 'การวางแผนโครงการ');

INSERT INTO pf_milestones (name, due_date, status, progress)
SELECT 'การออกแบบ UI', '2026-03-10', 'กำลังดำเนินการ', 60
WHERE NOT EXISTS (SELECT 1 FROM pf_milestones WHERE name = 'การออกแบบ UI');

INSERT INTO pf_milestones (name, due_date, status, progress)
SELECT 'พัฒนา Backend', '2026-03-15', 'กำลังดำเนินการ', 30
WHERE NOT EXISTS (SELECT 1 FROM pf_milestones WHERE name = 'พัฒนา Backend');

INSERT INTO pf_milestones (name, due_date, status, progress)
SELECT 'ทดสอบและเผยแพร่', '2026-03-20', 'ยังไม่เริ่ม', 0
WHERE NOT EXISTS (SELECT 1 FROM pf_milestones WHERE name = 'ทดสอบและเผยแพร่');

INSERT INTO pf_feedback (comment, instructor_name, date, project_name)
SELECT 'ความก้าวหน้าของการออกแบบ UI เป็นไปด้วยดี โปรดเน้นเรื่อง Responsive Design สำหรับอุปกรณ์มือถือเพิ่มเติม', 'ดร.สมหญิง มีชัย', '2026-02-28', 'โครงการพัฒนาเว็บไซต์'
WHERE NOT EXISTS (SELECT 1 FROM pf_feedback WHERE comment LIKE 'ความก้าวหน้าของการออกแบบ UI%');

INSERT INTO pf_feedback (comment, instructor_name, date, project_name)
SELECT 'โครงสร้างฐานข้อมูลมีความเหมาะสม แนะนำให้เพิ่ม Index เพื่อเพิ่มประสิทธิภาพ', 'ศ.ดร.สมชาย วิชาการ', '2026-02-27', 'การออกแบบฐานข้อมูล'
WHERE NOT EXISTS (SELECT 1 FROM pf_feedback WHERE comment LIKE 'โครงสร้างฐานข้อมูลมีความเหมาะสม%');

INSERT INTO pf_feedback (comment, instructor_name, date, project_name)
SELECT 'การเตรียมการเริ่มต้นดีมาก อย่าลืมทำเอกสารประกอบโค้ดให้ครบถ้วน', 'ดร.สมหญิง มีชัย', '2026-02-25', 'โครงการพัฒนาเว็บไซต์'
WHERE NOT EXISTS (SELECT 1 FROM pf_feedback WHERE comment LIKE 'การเตรียมการเริ่มต้นดีมาก%');

INSERT INTO pf_chart (course, projects, completed)
SELECT 'CS 101', 4, 3
WHERE NOT EXISTS (SELECT 1 FROM pf_chart WHERE course = 'CS 101');

INSERT INTO pf_chart (course, projects, completed)
SELECT 'CS 201', 3, 2
WHERE NOT EXISTS (SELECT 1 FROM pf_chart WHERE course = 'CS 201');

INSERT INTO pf_chart (course, projects, completed)
SELECT 'CS 301', 5, 1
WHERE NOT EXISTS (SELECT 1 FROM pf_chart WHERE course = 'CS 301');
