-- ========================================================
-- Supabase Cloud Schema for project_fiveper (Student Progress Tracking)
-- Comprehensive SRS-Aligned Schema V2.1-FINAL
-- Execute this SQL in Supabase SQL Editor (https://supabase.com/dashboard)
-- ========================================================

-- 1. Table: pf_users
CREATE TABLE IF NOT EXISTS pf_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('ผู้ดูแลระบบ', 'อาจารย์', 'นักศึกษา')),
  password_hash TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Table: pf_projects
CREATE TABLE IF NOT EXISTS pf_projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  course TEXT NOT NULL,
  due_date DATE,
  status TEXT DEFAULT 'กำลังดำเนินการ',
  student_id BIGINT REFERENCES pf_users(id) ON DELETE SET NULL,
  teacher_id BIGINT REFERENCES pf_users(id) ON DELETE SET NULL,
  student TEXT,
  progress INT DEFAULT 0,
  attachment_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Table: pf_project_members (Junction Table for Group Projects - FR-3.1)
CREATE TABLE IF NOT EXISTS pf_project_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT REFERENCES pf_projects(id) ON DELETE CASCADE,
  student_id BIGINT REFERENCES pf_users(id) ON DELETE CASCADE,
  role_in_team TEXT DEFAULT 'สมาชิก' CHECK (role_in_team IN ('หัวหน้าโครงการ', 'สมาชิก')),
  joined_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(project_id, student_id)
);

-- 4. Table: pf_milestones
CREATE TABLE IF NOT EXISTS pf_milestones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT REFERENCES pf_projects(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  due_date DATE,
  status TEXT DEFAULT 'ยังไม่เริ่ม',
  progress INT DEFAULT 0,
  is_approved BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Table: pf_feedback
CREATE TABLE IF NOT EXISTS pf_feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT REFERENCES pf_projects(id) ON DELETE CASCADE,
  instructor_id BIGINT REFERENCES pf_users(id) ON DELETE SET NULL,
  comment TEXT NOT NULL,
  instructor_name TEXT,
  date DATE DEFAULT CURRENT_DATE,
  project_name TEXT,
  is_read BOOLEAN DEFAULT FALSE,
  reply_comment TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Table: pf_notifications
CREATE TABLE IF NOT EXISTS pf_notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES pf_users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Table: pf_audit_logs
CREATE TABLE IF NOT EXISTS pf_audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES pf_users(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  details TEXT,
  ip_address TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Table: pf_chart
CREATE TABLE IF NOT EXISTS pf_chart (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course TEXT NOT NULL UNIQUE,
  projects INT DEFAULT 0,
  completed INT DEFAULT 0,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS and Allow Public Access Policies (for Demo)
ALTER TABLE pf_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE pf_projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE pf_project_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE pf_milestones ENABLE ROW LEVEL SECURITY;
ALTER TABLE pf_feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE pf_notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE pf_audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE pf_chart ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read pf_users" ON pf_users FOR SELECT USING (true);
CREATE POLICY "Allow public insert pf_users" ON pf_users FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update pf_users" ON pf_users FOR UPDATE USING (true);
CREATE POLICY "Allow public delete pf_users" ON pf_users FOR DELETE USING (true);

CREATE POLICY "Allow public read pf_projects" ON pf_projects FOR SELECT USING (true);
CREATE POLICY "Allow public insert pf_projects" ON pf_projects FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update pf_projects" ON pf_projects FOR UPDATE USING (true);
CREATE POLICY "Allow public delete pf_projects" ON pf_projects FOR DELETE USING (true);

CREATE POLICY "Allow public read pf_project_members" ON pf_project_members FOR SELECT USING (true);
CREATE POLICY "Allow public insert pf_project_members" ON pf_project_members FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update pf_project_members" ON pf_project_members FOR UPDATE USING (true);
CREATE POLICY "Allow public delete pf_project_members" ON pf_project_members FOR DELETE USING (true);

CREATE POLICY "Allow public read pf_milestones" ON pf_milestones FOR SELECT USING (true);
CREATE POLICY "Allow public insert pf_milestones" ON pf_milestones FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update pf_milestones" ON pf_milestones FOR UPDATE USING (true);
CREATE POLICY "Allow public delete pf_milestones" ON pf_milestones FOR DELETE USING (true);

CREATE POLICY "Allow public read pf_feedback" ON pf_feedback FOR SELECT USING (true);
CREATE POLICY "Allow public insert pf_feedback" ON pf_feedback FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update pf_feedback" ON pf_feedback FOR UPDATE USING (true);
CREATE POLICY "Allow public delete pf_feedback" ON pf_feedback FOR DELETE USING (true);

CREATE POLICY "Allow public read pf_notifications" ON pf_notifications FOR SELECT USING (true);
CREATE POLICY "Allow public insert pf_notifications" ON pf_notifications FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public read pf_audit_logs" ON pf_audit_logs FOR SELECT USING (true);
CREATE POLICY "Allow public insert pf_audit_logs" ON pf_audit_logs FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public read pf_chart" ON pf_chart FOR SELECT USING (true);
CREATE POLICY "Allow public insert pf_chart" ON pf_chart FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update pf_chart" ON pf_chart FOR UPDATE USING (true);
CREATE POLICY "Allow public delete pf_chart" ON pf_chart FOR DELETE USING (true);

-- Insert Default Initial Data
INSERT INTO pf_users (user_id, name, email, role) VALUES
('ADM001', 'ผู้ดูแลระบบ', 'admin@ku.th', 'ผู้ดูแลระบบ'),
('INS001', 'ดร.สมหญิง มีชัย', 'teacher@ku.th', 'อาจารย์'),
('STU001', 'สมชาย ใจดี', 'student@ku.th', 'นักศึกษา'),
('STU002', 'สมหญิง ใจงาม', 'somying.j@university.ac.th', 'นักศึกษา'),
('INS002', 'ศ.ดร.สมชาย วิชาการ', 'somchai.w@university.ac.th', 'อาจารย์')
ON CONFLICT (email) DO NOTHING;

INSERT INTO pf_projects (name, description, course, due_date, status, student, progress) VALUES
('โครงการพัฒนาเว็บไซต์', 'สร้างเว็บไซต์ที่รองรับหลายขนาดหน้าจอ', 'CS 101', '2026-03-15', 'กำลังดำเนินการ', 'สมชาย ใจดี', 75),
('การออกแบบฐานข้อมูล', 'ออกแบบและสร้างโครงสร้างฐานข้อมูล', 'CS 201', '2026-03-20', 'กำลังดำเนินการ', 'สมหญิง ใจงาม', 45),
('โมเดลแมชชีนเลิร์นนิง', 'ฝึกโมเดลการจำแนกประเภท', 'CS 301', '2026-04-01', 'ยังไม่เริ่ม', 'สมศักดิ์ ทรงไทย', 0),
('แอปพลิเคชันมือถือ', 'พัฒนาแอป Android และ iOS', 'CS 101', '2026-02-28', 'เสร็จสิ้น', 'พุทธพร เหลืองสีเพชร', 100);

INSERT INTO pf_milestones (name, due_date, status, progress) VALUES
('การวางแผนโครงการ', '2026-03-05', 'เสร็จสิ้น', 100),
('การออกแบบ UI', '2026-03-10', 'กำลังดำเนินการ', 60),
('พัฒนา Backend', '2026-03-15', 'กำลังดำเนินการ', 30),
('ทดสอบและเผยแพร่', '2026-03-20', 'ยังไม่เริ่ม', 0);

INSERT INTO pf_feedback (comment, instructor_name, date, project_name) VALUES
('ความก้าวหน้าของการออกแบบ UI เป็นไปด้วยดี โปรดเน้นเรื่อง Responsive Design สำหรับอุปกรณ์มือถือเพิ่มเติม', 'ดร.สมหญิง มีชัย', '2026-02-28', 'โครงการพัฒนาเว็บไซต์'),
('โครงสร้างฐานข้อมูลมีความเหมาะสม แนะนำให้เพิ่ม Index เพื่อเพิ่มประสิทธิภาพ', 'ศ.ดร.สมชาย วิชาการ', '2026-02-27', 'การออกแบบฐานข้อมูล'),
('การเตรียมการเริ่มต้นดีมาก อย่าลืมทำเอกสารประกอบโค้ดให้ครบถ้วน', 'ดร.สมหญิง มีชัย', '2026-02-25', 'โครงการพัฒนาเว็บไซต์');

INSERT INTO pf_chart (course, projects, completed) VALUES
('CS 101', 4, 3),
('CS 201', 3, 2),
('CS 301', 5, 1)
ON CONFLICT (course) DO NOTHING;
