spring.application.name=demo

spring.datasource.url=jdbc:mysql://localhost:8700/webdb
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 🔥 ปิด Docker Compose
spring.docker.compose.enabled=false
spring.docker.compose.lifecycle-management=none